# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-29 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20191129_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
