# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-29 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20191129_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
