# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Goods',
        ),
    ]
