# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_auto_20191130_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='gnumber',
            field=models.IntegerField(default=1),
        ),
    ]
