# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0013_auto_20191130_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnumber', models.IntegerField(default=1)),
                ('mygoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('role', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='shopcar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.UserInfo'),
        ),
    ]
