# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_auto_20191130_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.IntegerField(default=0)),
                ('ogoods', models.ManyToManyField(to='shops.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.UserInfo')),
            ],
        ),
    ]
