# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Goods')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='ogoods',
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='m',
            field=models.ManyToManyField(through='shops.OrderGoods', to='shops.Goods'),
        ),
    ]
