# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_ordergoods_goods_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0),
        ),
    ]
