# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_auto_20191201_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
    ]
