# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 1, 4, 25, 8, 840543)),
        ),
    ]
