# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_auto_20191201_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 4, 28, 22, 220872)),
        ),
    ]
