# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0021_auto_20191201_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='m',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordergoods',
            name='goods1',
        ),
        migrations.RemoveField(
            model_name='ordergoods',
            name='order1',
        ),
        migrations.RemoveField(
            model_name='shopcar',
            name='mygoods',
        ),
        migrations.RemoveField(
            model_name='shopcar',
            name='user',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderGoods',
        ),
        migrations.DeleteModel(
            name='ShopCar',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
