# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-30 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0022_auto_20191201_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.FloatField(default=0)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2019, 12, 1, 4, 33, 20, 954540))),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.IntegerField(default=1)),
                ('goods1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Goods')),
                ('order1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnumber', models.IntegerField(default=1)),
                ('mygoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('role', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='shopcar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.UserInfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='m',
            field=models.ManyToManyField(through='shops.OrderGoods', to='shops.Goods'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.UserInfo'),
        ),
    ]
