# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-02 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0023_auto_20191201_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 14, 25, 21, 226159)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
