# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-20 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UesrInfo',
            new_name='UserInfo',
        ),
    ]
