# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191120_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('publish_date', models.DateField()),
                ('publish', models.CharField(max_length=32)),
            ],
        ),
    ]
