# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-17 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_permission_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='access_name',
            field=models.CharField(max_length=32, verbose_name='权限名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.TopMenu', verbose_name='一级菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission', verbose_name='父级菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=2083, verbose_name='权限路径'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='路径别名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='weight',
            field=models.IntegerField(default=10, verbose_name='权重'),
        ),
    ]
