# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-17 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_permission_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=32, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='topmenu',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='topmenu',
            name='title',
            field=models.CharField(max_length=32, verbose_name='菜单名称'),
        ),
        migrations.AlterField(
            model_name='topmenu',
            name='weight',
            field=models.IntegerField(default=10, verbose_name='权重'),
        ),
    ]
